#!/bin/bash

. $(dirname $0)/lib/main.sh

url=http://sourceforge.net/projects/$package/files/$package/$version/jpegsrc.v$version.tar.gz

do_stage() {
    [ -f $pkgbuilddir/Makefile ] || do_build

    mkdir -p $pkginstalldir/bin
    mkdir -p $pkginstalldir/lib
    mkdir -p $pkginstalldir/include
    mkdir -p $pkginstalldir/man/man1

    cd $pkgbuilddir

    make install install-lib "${env[@]}" "${make_vars[@]}"
}

main "$@"
